#!/bin/sh
### BEGIN INIT INFO
# Provides:          collector
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: collector of wifi data
# Description:       Displays data found from Airmon and Airodump to track wifi mac addresses
### END INIT INFO
# Quick start-stop-daemon example, derived from Debian /etc/init.d/ssh
set -e

export PATH=$PATH:/usr/local/bin
export LOG_LEVEL=debug

NAME=collector

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

case "$1" in
  start)
    echo -n "Starting: "$NAME
    cd /home/pi/mozfest; foreman start > /var/log/$NAME_start.log 2>&1
    echo "."
    ;;
  stop)
    echo -n "Stopping: "$NAME
    cd /home/pi/mozfest; foreman stop > /var/log/$NAME_stop.log 2>&1
    echo "."
    ;;
  restart)
    echo -n "Restarting: "$NAME
    cd /home/pi/mozfest; foreman start > /var/log/$NAME_start.log 2>&1
    cd /home/pi/mozfest; foreman stop > /var/log/$NAME_stop.log 2>&1
    echo "."
    ;;

  *)

    echo "Usage: "$1" {start|stop|restart}"
    exit 1
esac

