#!/bin/sh
### BEGIN INIT INFO
# Provides:          wpa-cli-web
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Example initscript
# Description:       This file should be used to construct scripts to be
#                    placed in /etc/init.d.
### END INIT INFO
# Quick start-stop-daemon example, derived from Debian /etc/init.d/ssh
set -e

# Must be a valid filename
NAME=wpa-cli-web
PIDFILE=/var/run/$NAME.pid
#This is the command to be run, give the full pathname
#DAEMON=/usr/local/bin/wpa_cli_web
#DAEMON=/home/pi/mozfest
#DAEMON_OPTS="start -e production -p 8080"

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

case "$1" in
  start)
    echo -n "Starting: "$NAME
#    cd /home/pi/mozfest; /usr/local/bin/foreman start > /var/log/$NAME_start.log   2>&1
#    cd /home/pi/mozfest; /usr/local/bin/foreman start 2>&1 > $NAME_start.log
#    cd /home/pi/mozfest; sudo /usr/local/bin/foreman start 2>&1 > $NAME_start.log
    cd /home/pi/mozfest; nohup sudo /usr/local/bin/foreman start &
    echo "."
    ;;
  stop)
    echo -n "Stopping: "$NAME
    cd /home/pi/mozfest; sudo /usr/local/bin/foreman stop 2>&1 > $NAME_stop.log
    echo "."
    ;;
  restart)
    echo -n "Restarting: "$NAME
    cd /home/pi/mozfest; /usr/local/bin/foreman start > /var/log/$NAME_start.log 2>&1
    cd /home/pi/mozfest; /usr/local/bin/foreman stop > /var/log/$NAME_stop.log 2>&1
    echo "."
    ;;

  *)
    echo "Usage: "$1" {start|stop|restart}"
    exit 1
esac

exit 0
